### ISSUE TITLE
Put your project in the EnTT in Action list

### ISSUE THREAD

**Issue by skypjack** [guillaume-haerinck/imac-tower-defense#1]
Hi, sorry to bother you, I'm the author of `EnTT`.

I found your project and I think it's very interesting in many ways, from the documentation to the post-mortem part. Probably you already know that but I'm also trying to give the users of `EnTT` a few examples to give them inspiration and more when they take their first steps.

What do you think about putting your repo in [the list of projects](https://github.com/skypjack/entt/wiki/EnTT-in-Action) _made with `EnTT`_?
You can make a PR or just close the issue with a :+1: if you prefer, I'll add it for you.

**Comment by guillaume-haerinck** [comment]
I just made the Pull Request, thanks for the suggestion, it means a lot for us ! I'm using ENTT in different other projects, I'll be certain to notify it on your repo when they will be advanced enough 😀

**Comment by skypjack** [comment]
Sure, you're welcome! Examples are useful for newcomers. Thanks a lot. :+1:
